apiVersion: databases.database-operator.io/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: database-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  # TODO(user): Add fields here
